### ISSUE TITLE
Create mockup of home page

### ISSUE THREAD

**Issue by devgav** [a-doe-bo/hi-doe-bill-tracker#1]
Please do work for this task in a branch called issue-01.

## Features
List of bills
Sort bills by priority
Calendar & Clock

**Comment by Kobeyarai808** [comment]
Add image of the mockup

**Comment by devgav** [comment]
![Image](https://user-images.githubusercontent.com/69144726/187790607-901c78ff-24b9-49c8-a62a-8e6d0e68a297.png)
