### ISSUE TITLE
Create a mockup of "Saved Bills" page for secretary

### ISSUE THREAD

**Issue by devgav** [a-doe-bo/hi-doe-bill-tracker#10]
Please do work for this task in a branch called issue-10.

**Comment by michnotmeesh** [comment]
Should be a list of bills. When the user clicks a bill, they can view it. There should be a "Assign to Expert" button.

**Comment by jwu0** [comment]
![Image](https://user-images.githubusercontent.com/77696993/188763355-f05ae979-719d-48f2-af43-339f795b5e2b.png)
