### ISSUE TITLE
Bill Hearing Scheudling mockup

### ISSUE THREAD

**Issue by devgav** [a-doe-bo/hi-doe-bill-tracker#15]
Please do work for this task in a branch called issue-15.

****Component of view bill page.
Display location, time, and what bill they are having the hearing for.

(Simple UI has: Time, Bill No. , zoom link/room number, topic -> can click to get the full info)

**Comment by LiLiang808** [comment]
On September 8, we decided that it doesn't need to be component, can be intergrate into view bill page on the team meeting
