### ISSUE TITLE
Email Mockup - What the client sees with the email sent

### ISSUE THREAD

**Issue by devgav** [a-doe-bo/hi-doe-bill-tracker#19]
Please do work for this task in a branch called issue-19.

## Features
Hearing notices
Links to bill
Link to bill log diff
Calendar scheduler/reminder <button>(google calendar api) (low priority)
Table design???

**Comment by Thaneluna** [comment]
![Image](https://user-images.githubusercontent.com/42688917/187598109-26e3a476-8691-4d4d-8e84-276e2c392ee8.PNG)
