### ISSUE TITLE
Create navbar component

### ISSUE THREAD

**Issue by devgav** [a-doe-bo/hi-doe-bill-tracker#40]
Please do work for this task in a branch called issue-XXX.

**Comment by magnusfarstad** [comment]
All logged in users:
  - List Bills
  - Saved Bills
  - Profile
Navbar for Admin:
  - create account 
  - List accounts
  - Requested Accounts
Navbar for Secretary
  - Request account creation
  - Saved bills
Navbar for PIPE Approver, Office Approver, Final Approver
  -
