### ISSUE TITLE
Create "Pagination" 

### ISSUE THREAD

**Issue by devgav** [a-doe-bo/hi-doe-bill-tracker#66]
Please do work for this task in a branch called issue-XXX.

There should be functionality to this pagination. Don't close this ticket until that is accomplished.

**Comment by adrianwtam** [comment]
Pagination scripting is partially done

+Pagination Bar works by dynamically shifting to fit the numPages based off of numBills/numBillsPerPage
  (It tries to fit a max of 10 indexes, but reduces if there isn't enough pages)
-Need to connect it to pages that need pagination and create another component/script that filters the Bill Data based on the pagination Bar
-Need to add functionality to Last/First/Prev/Next buttons in Pagination Bar
