### ISSUE TITLE
Review: Landing.jsx and UserPage.jsx

### ISSUE THREAD

**Issue by Kobeyarai808** [a-doe-bo/hi-doe-bill-tracker#88]
## Overview

The focus for this code review will be centered around the Landing and User page.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-3

## Files to review

* [Landing](https://github.com/a-doe-bo/hi-doe-bill-tracker/blob/main/app/imports/ui/pages/Landing.jsx)
* [UserPage](https://github.com/a-doe-bo/hi-doe-bill-tracker/blob/main/app/imports/ui/pages/UserPage.jsx)

## Checklists

* [Architecture](../../checklists/architecture-checklist.md)
* [Design](../../checklists/design-checklist.md)
* [JS](../../checklists/js-checklist.md)
* [React](../../checklists/react-checklist.md)
* [Testing](../../checklists/testing-checklist.md)

## Due date

27, September 1:30 pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by adrianwtam** [comment]
**Landing.jsx**
Line 11: Is there really a need to use a custom logo rather than HIDOEs logo
Line 28: Why do we have an href to localhost URL instead of a Route and Path?
              Won't the code have to be changed every time it hits a new server?

**User Page.jsx**
Seems fine atm as a sample page

Next step is to add functionality so that it can get actual data from settings.development.json
Prioritize doing it after doing the issue: Fill settings.development.json with fake profile data

Maybe later fill it with useless stats like:
-Working since 20XX
-Number of Bills Contributed to
-Amount of Bills Passed
-Expertise Graph etc.

**Comment by magnusfarstad** [comment]
#### Landing.jsx
* `<br />` use generally not practical in the long run. Maybe we can use CSS here?
#### UserPage.jsx
* L8-14: Indicates hardcode

**Comment by Kobeyarai808** [comment]
Landing.jsx
Line 11: The logo in the landing page is different from the one on the navbar
Line 28: replace hrefs with React routes

User Page.jsx
Lines 8-14: Why are we declaring mock data here, it should go to settings.development.json
Lines 23-27: This should be dynamic based on what user is logged in

**Comment by Thaneluna** [comment]
Landing.jsx
DE-05:
Line 5 Unecessary comment

Line 28
Use React Button not button

UserPage.jsx
Line 19: Use Card since you are using Card components
Line 7:
TODO: Get collection data from user collection

**Comment by joshmcons** [comment]
UserPage.jsx:
Hard code, get data from user collection

Landing.jsx:
Use a Route and Path instead of localhost

**Comment by devgav** [comment]
Landing.jsx 
- Remove unnecessary comments (line 5)
- a tag comments can be made to link (line 28-29)
- use react instead of button (linei 28-29)
UserPage.jsx

- use card component

**Comment by jwu0** [comment]
Landing.jsx
Line 11 - Logo is different from navbar
Line 28 - Should use something else other than href to local host

UserPage.jsx
Line 28 - Use card components instead

**Comment by Cole-House** [comment]
Landing.jsx:
- Line 28: use the React Button instead
UserPage.jsx
- Might want to use card component
